version: '3'
services:
  grafana:
    image: playneta/statistics:grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: qwerty

    volumes:
      - .dev/grafana:/var/lib/grafana

    ports:
      - 3000:3000


